version: '3.8'

services:
  warpfactory-dev:
    build: .
    container_name: warpfactory_conversion
    volumes:
      - .:/WarpFactory
      - ./.claude_docker1:/home/warpuser/.claude
    working_dir: /WarpFactory
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
      - JUPYTER_ENABLE_LAB=yes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: /bin/bash
