version: '3.8'

services:
  warpfactory-dev:
    build: .
    container_name: warpfactory_conversion
    volumes:
      - .:/WarpFactory
      - claude_data:/home/warpuser/.claude
      - /opt/matlab:/opt/matlab:ro
      - /home/jon/.matlab/R2023b_licenses:/home/warpuser/.matlab/R2023b_licenses:ro
      - matlab_prefs:/home/warpuser/.matlab/R2023b
    working_dir: /WarpFactory
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
      - JUPYTER_ENABLE_LAB=yes
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: /bin/bash

volumes:
  claude_data:
  matlab_prefs:
